// <auto-generated />
namespace F2022A6DSB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trackeditview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trackeditview));
        
        string IMigrationMetadata.Id
        {
            get { return "202212081750045_track-edit-view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
