// <auto-generated />
namespace F2022A6DSB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class firstartistviewupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstartistviewupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202212070008510_first-artist-view-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
